
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/agap_management
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8080

application:
  security:
    jwt:
      secret-key: cNYIfqkRXwKcwvywkb0WkkfYX2l7OLLaSvs3ga6NcnY=
      expiration: 240000              # a day=86400000,  minute=60000
      refresh-token:
        expiration: 600000            # 7 days 604800000

# Java
  #mail:
  #host: localhost
  #port: 1025
  #username: ali
  #password: ali
    #properties:
      #mail:
        #smtp:
        #trust: "*"
      #auth: true
        #starttls:
        #enabled: true
      #connectiontimeout: 5000
      #timeout: 3000
      #writetimeout: 5000


logging:
  level:
    com.agap.management.infrastructure.security.JwtAuthenticationFilter: ERROR
    org.springframework.security: ERROR
    org.springframework.web: ERROR


